### ISSUE TITLE
Issue when doing server side rendering

### ISSUE THREAD

**Issue by tornikenats** [jelleklaver/react-linkedin-insight#1]
When you try to use this plugin with an app that uses SSR, there is an error regarding window variable not existing.

**Comment by jelleklaver** [comment]
Thanks for submitting this issue. I haven't yet taken SSR into account. What should be expected behaviour? I think the insight tag should not be triggered during SSR because it is actually not a page visit and it will be triggered when the user actually loads the page.

**Comment by tornikenats** [comment]
@jelleklaver I agree. Thanks for creating the change! When do you think you'll merge it in?

**Comment by jelleklaver** [comment]
@tornikenats I still had to test it and change the webpack config. I've merged and pushed to npm now. Hope you enjoy it!
