### ISSUE TITLE
Files List Incomplete

### ISSUE THREAD

**Issue by davidtollefson** [jelleklaver/react-linkedin-insight#11]
Had to use previous build due to incomplete files list for the package.

v0.1.0 provided an empty object for me (missing types). Other builds work well.

**Comment by jelleklaver** [comment]
Hi @davidtollefson, could you please provide some more context? The related code and the full error message, please :)

**Comment by davidtollefson** [comment]
Generally, types are not included when someone installs this package.

They can included in the files parameter or types parameter of package.json.

Initiializing returned an empty object using v0.1.0, but not with v0.0.5

**Comment by jelleklaver** [comment]
Sorry for my late reply, I totally missed your response. I'm not really sure what happens, as I don't use it with Typescript myself. But v0.0.5 certainly doesn't have any types at all. The files list hasn't changed, however, we did add the following:

```js
...
  "types": "./@types/index.d.ts",
...
```

Would it mean that we'd also have to add the `@types` directory to the `files` in `package.json`?

**Comment by jelleklaver** [comment]
@davidtollefson I just published verson 0.1.1 to include the `@types` directory (and thus the types...), I hope it will solve the issue. Could you please verify it for me? Thanks!
