### ISSUE TITLE
Types not working in Typescript

### ISSUE THREAD

**Issue by WillSquire** [jelleklaver/react-linkedin-insight#20]
Using:

```ts
import LinkedInTag from 'react-linkedin-insight'
```

Produces `any`. Using:

```ts
import * as LinkedInTag from 'react-linkedin-insight'
```

Gets the types, but crashes in runtime (webpack).

**Comment by jelleklaver** [comment]
Thanks for raising an issue. I'm far from an expert on Typescript myself, but I'm happy to merge a pull request to resolve this issue. In the mean time, you can add `// @ts-ignore` before `import LinkedInTag from 'react-linkedin-insight';` as a workaround (as proposed in https://github.com/jelleklaver/react-linkedin-insight/issues/4#issuecomment-731207954).

**Comment by jelleklaver** [comment]
Hi @WillSquire, I figured the following should work: https://github.com/jelleklaver/react-linkedin-insight/commit/49cdb274d7450804f7d5e32671a679865bae11eb

Can you test if using this new type definition resolves your issue? If so, I'll merge and make a new release.
