### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by williamgoodhew** [jelleklaver/react-linkedin-insight#4]
Could not find a declaration file for module 'react-linkedin-insight'. '/path/node_modules/react-linkedin-insight/dist/linkedin-insight.js' implicitly has an 'any' type.
  Try `npm install @types/react-linkedin-insight` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-linkedin-insight';`ts(7016)

I have tried to do npom install --save  @types/react-linkedin-insight but get the following error.

`Not Found - GET https://registry.npmjs.org/@types%2freact-linkedin-insight - Not found`

**Comment by jelleklaver** [comment]
Hi @williamgoodhew,

Thanks for reaching out. Currently it doesn't actively support TypeScript. Feel free to open a pull request to add support. I'm happy to merge it.

**Comment by jelleklaver** [comment]
I see that @tattali forked this repo and added subdomain and ts support: [/tattali/react-linkedin-insight](https://github.com/tattali/react-linkedin-insight). Maybe he can help you/submit a PR?

**Comment by teslavitas** [comment]
you can add `// @ts-ignore` before` import LinkedInTag from 'react-linkedin-insight';` as a workaround.

**Comment by tattali** [comment]
> I see that @tattali forked this repo and added subdomain and ts support: [/tattali/react-linkedin-insight](https://github.com/tattali/react-linkedin-insight). Maybe he can help you/submit a PR?

Hi ! Yes I use the fork with this in my `package.json`
```json
{
  "name": "frontend",
  "version": "0.1.0",
  "dependencies": {
    "react-linkedin-insight": "tattali/react-linkedin-insight#master"
  }
}
```

I rewrite it pretty much so becareful if you want to use it

**Comment by jelleklaver** [comment]
Thanks a lot @tattali! I've worked with your changes and published version `0.1.0` to npm with typescript and subdomain support. It should be backwards compatible with `0.0.5`. But I cannot guarantee backwards compatibility for each use case, so be sure to test it before updating!

**Comment by tattali** [comment]
Hi @jelleklaver. Thanks for the merge !

I'm glad you made the changes, this is proper than ever now.

But if I may, why is the `conversionId` prop of the` track` function optional?

Thanks

**Comment by jelleklaver** [comment]
@tattali This way it can make a tracking call (still using the `partnerId`) without a specific conversion set. I don't really use the Insight Tag any more myself, but I guess it might be used for tracking simpler things like regular page loads etc. I could be wrong, but if LinkedIn doesn't support it, they probably should ;-)
